services:
  - type: web
    name: signature-app-frontend
    runtime: node
    buildCommand: npm install && node node_modules/vite/bin/vite.js build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
